try:
    print(x) #x is not defined here
except:
    print("An exception occured")
